App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [new, edit]
    longitude:
      - Range:
          min: -180
          max: 180
          groups: [new, edit]

App\Entity\Measurement:
  properties:
    date:
      - NotBlank:
          groups: [new, edit]
    celsius:
      - NotBlank:
          groups: [new, edit]
      - Range:
          min: -50
          max: 50
          groups: [new, edit]
    humidity:
      - NotBlank:
          groups: [new, edit]
      - Range:
          min: 20
          max: 90
          groups: [new, edit]
